### ISSUE TITLE
no g++ installed! :D

### ISSUE THREAD

**Issue by r-lyeh** [RandyGaul/kk_slides#1]
https://github.com/RandyGaul/kk_slides/blob/f0de4bc9b0c966a16db562edbcac79a40733f3ba/main.cpp#L91

**Comment by r-lyeh** [comment]
ps: why dont you compile this in .sln ?

**Comment by RandyGaul** [comment]
That would work!

I use tdm-gcc, it’s a very small distro for Windows. Only takes a couple minutes to install.

**Comment by r-lyeh** [comment]
Or you can also embed tcc! which was 274 kb in 2008 rev

tcc-0.9.24-win32-bin.zip | 274K
http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.24-win32-bin.zip

**Comment by RandyGaul** [comment]
As in, embed it in the exe, save it to disk at run-time, and then use that from the command line instead?

o_o

**Comment by r-lyeh** [comment]
Nope, just having a tcc\ folder in the repo and exec("tcc/tcc.exe"...) instead (for _WIN32 case).
It's a full featured C compiler in 274K, so minimal fuss that wont require users to install a secondary compiler (we're aiming at MSC+gcc right now). In fact, you could get rid of that .sln and use a small batch that compiles only with provided tcc/ folder.

Non win32 users could still exec("gcc"...) as it's used everywhere else :D

**Comment by r-lyeh** [comment]
Got some spare time and created a pure C version from this; which you can see in my fork. Also removed msvc/gcc dependency as discussed above (by embedding tcc compiler).
Finally got to see the full demo :D
Very nice indeed.

Small fixes:
1. typedef struct and enums in slides, so they compile as both C and C++.
1. popen/fclose -> popen/pclose.
1. remove \r linefeeds in commands "@clear\r" -> "@clear"

Let me know if you want to PR this to somewhere else (master or branch)

**Comment by RandyGaul** [comment]
PR it up!

**Comment by RandyGaul** [comment]
Seems very cross platform now. Cool! I learned a couple nice tricks from you here as well, so thanks a lot! :)

**Comment by r-lyeh** [comment]
cool! btw, your coroutine.h impl is one of the coolest around :D will use it someday when adding scripting to my engine

**Comment by RandyGaul** [comment]
I use it for all my gameplay! It actually took a year to design and went through iterations over time :)

APIs take a lot of effort

**Comment by r-lyeh** [comment]
PS: love the fact that each main .gif is way bigger than the whole tcc/ folder!
